language: java
jdk:
- oraclejdk8
notifications:
  slack:
    secure: Vih8u/aCh3t1vWdWNJzJTpnBJ3ho+ILv7Mn5Dwz1sZ9Vg0YyTCTtKaeG8XIUz2v5b0wE/ZQoMox/s6oUuc2zu/TbVs05Kw9zpU81bI0X/atGRcSkLKNbYQrl5HTgifBkTpvOvhUZC4CuJoSwKRWB7PueYdzj35FETIFO6jfoYzSm5UA8X4Nd52x8YHHZ9MC8R5f6a1ElAgQF+iClbQLLPJBJ4E8u7rqQ6/7lzrZWrXYt3M2Oecs7vOLUTimpKpNu3lvA7/Kd7HpTlJfGi3tb0e9IzDDzt6ojzXYUuLKr5YbtCMMDjiYINuj7x45Wib/QxDi/R7N5zkWMf9Sjhgsiv8+NmMMn1flcSIB4QQnPOjURwUccfr/I6GgZuDSIWVuHDsjiKj5o4VddGoMfLk/zWQOGURJstEFmO+rD+PcF4JdWjH9bsdKloziKWRW7L6gze3dkwf+Dmd2Sp3VIpOugsq7uk2rnddNnjMHOdnzi4SfftZL/APYpXSBz9G9F+X5PGkTVVEb0cNYSnwfMrcXS3jLSbbmspbosnlbsL9853vsu0FlZfwjxJg1hIsfuV8fHU5ehr+tNDd1yFmbFXXgwx+Q1z/+pGYl6nHnEGLXfPXClC2SlwJGSVlAJoewH2NPSNhwiZYQjkI3603xrsRWJP8ibSCNDfuPQuWvSUoa9QUs=
